### ISSUE TITLE
Login UI

### ISSUE THREAD

**Issue by bmonish** [smart-india-apps/agrofresh#2]
@EthicalHitler Work on the designs

**Comment by EthicalHitler** [comment]
Done!
![Log in](https://user-images.githubusercontent.com/62928519/101733847-76346880-3ae5-11eb-906b-86197457eb69.png)
![Sign up](https://user-images.githubusercontent.com/62928519/101733855-792f5900-3ae5-11eb-8e01-53b3d43560f4.png)

**
